M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-07-31T11:14:11+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-31T11:14:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
%
G90
G05
T1
X152.0Y-71.0
T2
X160.6Y-65.0
X167.4Y-65.0
T3
X110.0Y-107.0
X115.5Y-107.0
T4
X128.0Y-131.0
X135.5Y-83.5
X135.5Y-132.5
X193.5Y-83.5
X197.0Y-76.5
M30
