M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-07-30T20:32:05+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-30T20:32:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X157.0Y-84.0
T2
X110.7Y-89.5
X116.2Y-89.5
T3
X103.5Y-90.5
X123.5Y-97.5
X181.5Y-97.5
X184.5Y-89.5
M30
